### ISSUE TITLE
Shiftwidth flicker on file enter

### ISSUE THREAD

**Issue by ram02z** [gpanders/editorconfig.nvim#1]
### How to reproduce
- Open a file that has a different shiftwidth than default.
- You will see a slight flicker where the indent size is set to the defined size i.e. 4 spaces

I can only reproduce this successfully on lower spec devices since startup is slower. The issue lies here, which as I understand is used to ensure editorconfig has the highest precedence.

https://github.com/gpanders/editorconfig.nvim/blob/eb319ca27f8a3e7d8b56d71e4a66849969c31cb8/plugin/editorconfig.vim#L31

![flicker](https://user-images.githubusercontent.com/59267627/129460170-21c63d43-23bf-48a8-96c6-14dc39993e60.gif)

**Comment by gpanders** [comment]
Thanks for the report. This should be fixed in fc45cdeb.
