### ISSUE TITLE
Provide a config key to disable the plugin

### ISSUE THREAD

**Issue by krishnakumarg1984** [gpanders/editorconfig.nvim#10]
I understand that as per the editorconfig specification, config files named `.editorconfig` will be recursively searched until the home drive/root file is found. If a project local `.editorconfig` is found, then those settings will be applied.

Now consider the following scenario.

If we are collaborating on a project with other project members, and the project doesn't use editorconfig spec, I'd like to instead conform to the already existing formatting standards (e.g. using the `indent-o-matic` plugin for indent detection). In this instance, I'd like to disable the `editorconfig.nvim` plugin selectively for that project alone using a project local `vimrc/init.lua` (facilitated using the `nvim-config-local` plugin). The plugin won't go searching and applying my root `.editorconfig` settings on a project with different formatting settings.

Thus, I shall be able to selectively enable and disable `editorconfig.nvim` depending on the project. You can leave it `enable = true` as default to not break the behavior for existing users of this plugin. 

Finally, could you please also add a key `silent = true | false` that will print a message to the console e.g. _"Editorconfig setting applied"_ using `vim.notify` for `silent=false`?  This will help to quickly track down the reason for any formatting changes in a large-scale collaborative project.

**Comment by gpanders** [comment]
Set `vim.g.loaded_editorconfig = 1` in your project local init.lua. That will prevent the plugin from loading.

As to your second request, editorconfig.nvim already sets a buffer local variable with the settings it’s applied for debugging purposes. This plugin currently does not have any configuration options and I’d like to keep it that way. I am also not crazy about the idea of supporting custom keys in the .editorconfig file.

With a small amount of Lua code, you could quite easily replicate this feature yourself with a `BufNewFile,BufRead,BufFilePost` autocommand that checks for the existence of the `b:editorconfig` buffer variable and calls `vim.notify` with its value.

**Comment by krishnakumarg1984** [comment]
Thank you for your response,

>I am also not crazy about the idea of supporting custom keys in the .editorconfig file.

Perhaps you misunderstood? I meant supporting keys in the config dict/table.

**Comment by gpanders** [comment]
I was interpreting your suggestion in two possible ways: adding a key to .editorconfig or adding a configuration key. However, as I said above this plugin currently has zero configuration and I’d like to keep it that way.

**Comment by gpanders** [comment]
I'm going to close this as there's nothing actionable and I've addressed the question in the issue title.

**Comment by mcepl** [comment]
> However, as I said above this plugin currently has zero configuration and I’d like to keep it that way.

I was not thinking about configuration, more about plugins. I am the author of https://github.com/editorconfig/editorconfig/issues/315 ... proposal for `spell_language` property. Although, it has not been accepted yet (and probably will never be, because Microsoft guys don’t care about non-programmers apparently), I could create https://gitlab.com/mcepl/editorconfig-vim-spell as the reference implementation plugin for https://github.com/editorconfig/editorconfig-vim.

How to create such plugin for editorconfig.nvim (I way prefer Lua to VimScript)?

**Comment by gpanders** [comment]
If it is accepted by editorconfig.vim I would implement that feature in this plugin too. Of course, one benefit of this being a Neovim-specific plugin is that we can do Neovim-specific things, without concern for the broader EditorConfig ecosystem. So if you want to open a PR for your proposal in this repo, I would take a look at it.

**Comment by mcepl** [comment]
Well, given the age of my proposal, I have stopped holding my breath when I was completely blue. And it has been couple of years ago. I completely understand that you don’t want to have included in your plugin any junk anybody can come up with (just the list of what VS Code supports makes me shiver), so possibility of ad-hoc plugins seems like a good compromise.

**Comment by gpanders** [comment]
The downside to allowing custom keys is that would preclude editorconfig.nvim from telling the user when they have an invalid property in their .editorconfig file. This is useful to let users know if they accidentally mistyped a property name, for instance.

However, I'm starting to reconsider this. Tim Pope's vim-sleuth (which also parses .editorconfig files) supports a custom `vim_filetype` property. And I'd like editorconfig.nvim to not freak out if it encounters an .editorconfig file with that property.

**Comment by gpanders** [comment]
I've had a change of heart. As of https://github.com/gpanders/editorconfig.nvim/commit/3067776653f2ccb358c472f544aa36a68e7974a7 editorconfig.nvim supports custom properties.
