### ISSUE TITLE
Could you add installation instructions?

### ISSUE THREAD

**Issue by JamyGolden** [gpanders/editorconfig.nvim#11]
I'm having problems getting this to work, and I'm not sure if it's because I've done something non-standard or if there are missing instructions. It would be nice to have packer, for example, installation instructions included.

**Comment by gpanders** [comment]
`use 'gpanders/editorconfig.nvim'` should be all you need.

I am not going to add package manager specific installation instructions are there are so many and the popular package manager of choice changes frequently. However, I did add a generic installation blurb to the README.

**Comment by JamyGolden** [comment]
<img width="1009" alt="Screenshot 2022-08-04 at 15 20 50" src="https://user-images.githubusercontent.com/602472/182857355-b35da6a9-e16b-46ca-9e24-dc15a2dbef3a.png">

I'm not sure if this is something new, but it doesn't seem to work with packer. I've retried multiple times with the same result.

**Comment by gpanders** [comment]
packer just uses git under the hood. Try navigating to the directory (`cd ~/.local/share/nvim/site/pack/packer/start/editorconfig.nvim`) and running

```
git fetch
git reset --hard origin/master
```

I'm not sure why it's failing, this plugin isn't doing anything fancy or different that would cause that.
