### ISSUE TITLE
Question: How editorconfig.nvim looks for .editorconfig file in directory?

### ISSUE THREAD

**Issue by shaeinst** [gpanders/editorconfig.nvim#12]
If I'm not wrong, editorconfig.nvim first looks in current directory, then previous and so on (```../``` ```../../```, ```../../../```).

**Comment by gpanders** [comment]
Yes, it traverses up the directory tree until it either 1) finds an .editorconfig file with `root = true` set or 2) it hits the root of the file system

**Comment by shaeinst** [comment]
how about using  ```vim.fn.getcwd()``` instead? or at least having option to set where ```editorconfig.nvim``` should look for ```.editorconfig``` file?.

**Comment by gpanders** [comment]
The file is found in accordance with the EditorConfig specification. There’s no reason to change it.

**Comment by shaeinst** [comment]
this make sense, specially when we have multiple .editorconfig files in different directory under same project.
