### ISSUE TITLE
Debug if plugin has found editorconfig or not

### ISSUE THREAD

**Issue by Lilja** [gpanders/editorconfig.nvim#13]
I'm testing out this plugin and am having trouble getting it work for my `<<`/`>>` needs. Pressing `>>` makes a typescript file I'm editing indent 8 spaces:
```
:set shiftwidth?
  shiftwidth=8
```
I'm editing a file that lies in `./app/src/api.ts`, editorconfig exists in `./.editorconfig`. I'm opening up the file through `telescope`.
```editorconfig
# ./.editorconfig
root = true

[*]
end_of_line = lf
insert_final_newline = true

[**.ts]
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
insert_final_newline = true
charset = utf-8

[*.ts]
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
insert_final_newline = true
charset = utf-8
```
Indent: `<<` and then `>>`
```TypeScript
// ./app/src/api.ts
export async function foo(
        tiles: string,
        letter_usage: LetterUsage
): Promise<any> {
        const response = await fetch('localhost', {
                headers: {
                        "content-type": "application/json",
                },
                method: "POST",
                body: JSON.stringify({
                        tiles: tiles.toLowerCase(),
                        letter_usage,
                })
        })
                                const res = await response.json()
        console.log(res)
        return res
}
```

* Shouldn't `>>` produce an indent of shiftwidth=2?
* Is there a way to debug if this plugin found an .editorconfig or not and applied settings?

**Comment by gpanders** [comment]
>Is there a way to debug if this plugin found an .editorconfig or not and applied settings?

Check for the `editorconfig` buffer variable:

`:echo b:editorconfig`

**Comment by Lilja** [comment]
Hmm, interesting. Seems like I'm unable to replicate the issue, good to know about that buffer variable!
