### ISSUE TITLE
Feature request: Add support for 'default editorconfig'

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [gpanders/editorconfig.nvim#14]
It would be cool if it was possible to specify the path to the default editor config which would be used in case no editor config file was found

**Comment by gpanders** [comment]
You can already do this by just creating a `.editorconfig` file in your home directory.

**Comment by gytis-ivaskevicius** [comment]
yeah, i considered it. Bit of a nasty solution also non xdg compatible :/
