### ISSUE TITLE
An invalid .editorconfig file breaks PackerSync

### ISSUE THREAD

**Issue by herrbischoff** [gpanders/editorconfig.nvim#19]
I've already opened an issue at https://github.com/wbthomason/packer.nvim/issues/1008, detailing the problem. In the interest of not repeating information, I'm not re-posting it here.

The short summary being, that the presence of an invalid `.editorconfig` file in the working directory leads to `:PackerSync` breaking down entirely and leaving Neovim in an unusable state. I believe that either the plugin or the plugin manager (or both) should guard against such exceptions with a sensible error message as opposed to breaking down.

You can reproduce this behavior with an `.editorconfig` file containing

```
[site/templates/**.{php]
indent_size = 2
```

which is clearly invalid because it misses a closing curly brace. When running `:PackerSync`, the environment breaks down.

**Comment by gpanders** [comment]
Should be addressed in 7d10fe6.
