### ISSUE TITLE
VimEnter autocommand only applies editorconfig to one buffer if multiple buffers are opened on startup

### ISSUE THREAD

**Issue by zeertzjq** [gpanders/editorconfig.nvim#2]
Is there a solution for this? Probably using `nvim_list_bufs()` and `nvim_buf_set_option()`?

**Comment by gpanders** [comment]
Good find. I think all we need to do is iterate over all open buffers in the `s:load()` function in `plugin/editorconfig.vim` and call `require('editorconfig').config()` for each.

**Comment by gpanders** [comment]
Should be fixed in 6204f8ba4. Please re-open if not.

**Comment by zeertzjq** [comment]
> It seems to still use `vim.bo`, which only applies to current buffer.

@gpanders

**Comment by gpanders** [comment]
Ah yep, again good catch. Give `master` a try again.
