### ISSUE TITLE
Support `max_line_length = off`

### ISSUE THREAD

**Issue by ObserverOfTime** [gpanders/editorconfig.nvim#21]
It's in the [spec](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length):

> Forces hard line wrapping after the amount of characters specified.
> `off` to turn off this feature (use the editor settings).
> 
> **Possible Values**
> 
> - positive integers
> - `off`

**Comment by gpanders** [comment]
Fixed in 4a8ecd3d. Thanks!
