### ISSUE TITLE
Question: Does after/ftplugin override the editorconfig?

### ISSUE THREAD

**Issue by Nikola-Milovic** [gpanders/editorconfig.nvim#22]
Hello, I have a simple question, will `after/ftplugin` override the `.editorconfig`? I am suspecting that it will

I have the following sets in my `go.lua` in `after`
```
vim.opt_local.commentstring = "//%s"
vim.opt_local.expandtab = false
vim.opt_local.shiftwidth = 4
vim.opt_local.softtabstop = 4
vim.opt_local.tabstop = 4
vim.opt.listchars = "eol:$"
```

And my `.editorconfig`
```
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

I am not well versed in these options so I am not 100% what's gonna happen when these mix

**Comment by gpanders** [comment]
No, EditorConfig takes precedence above everything else. This plugin fires on the same autocommands that filetype detection uses (namely `BufRead` and `BufNewFile`), but goes out of its way to ensure that's autocommmand runs last. So all of the ftplugin files will execute first, then the editorconfig file is parsed and applied.
