### ISSUE TITLE
Editorconfig is ignored after #24

### ISSUE THREAD

**Issue by dundargoc** [gpanders/editorconfig.nvim#25]
It seems to ignore the settings in editorconfig. If I open multiple buffers then only the first buffer seems to ignore editorconfig, all of the other buffers work correctly.

I can provide more reproduction steps if needed.

**Comment by gpanders** [comment]
FFS, I swear I tested it. Oh well, it was kind of a hack anyway so not too surprising that it's fragile.

I think the most straightforward way to do this is to just put the plugin file in the `after/` directory. That won't guarantee that the autocommand is defined last, but that ought to cover *most* cases.
