### ISSUE TITLE
Trim trailing whitespaces break undo tree

### ISSUE THREAD

**Issue by fragov** [gpanders/editorconfig.nvim#26]
May you add an option to turn off some rules? Or possibly fix an issue, which I describe next: 

Before I had no problem with this editorconfig, but lately, I've got a project, where property trim_trailing_whitespaces set to true. When I use d or x, and I get a line with end space in it, plugin trim it. Then if I try to undo it, whitespace appears for a second and then again removed by editorconfig-plugin. I can press `u` fast enough 2 times, then I get next undo in history-tree. But if I use redo command, then things get worse. Undo-tree get another branch in it, and I have to use `earlier` command to get forward in undo-tree because `<C-r>` not working after whitespace is removed.

Thank you!

**Comment by gpanders** [comment]
Please test the `undojoin` branch: https://github.com/gpanders/editorconfig.nvim/pull/27

**Comment by fragov** [comment]
Thank you a lot! I think it resolved my issue. Undo and redo works fine now.
