### ISSUE TITLE
insert_final_newline  does not work

### ISSUE THREAD

**Issue by cathaysia** [gpanders/editorconfig.nvim#29]
please see these screenshot:

![图片](https://user-images.githubusercontent.com/42114817/205304500-d1f5ff4a-cd38-4b42-8626-38162a8b1195.png)

before

![图片](https://user-images.githubusercontent.com/42114817/205304563-59a8e1ff-a2dc-4a08-b396-d8b3139d0539.png)

after save:

![图片](https://user-images.githubusercontent.com/42114817/205304641-bfc055d1-5d4d-48df-8e28-ab6d2a7ef0a6.png)

after reread:
![图片](https://user-images.githubusercontent.com/42114817/205304730-48d3cfe4-6e60-43c7-9299-28a4344ae059.png)

**Comment by gpanders** [comment]
The `insert_final_newline` directive simply means that the file should always have a newline (`\n`, 0xa) as its final character. This is what the both the plugin and Neovim ensure, so this is working as intended. You can verify this for yourself by inspecting the contents of your file with a hex editor (e.g. `xxd`). You will see that the last character is `0x0a`.

It does *not* mean there is a trailing empty line (which is really just two consecutive newline characters).

**Comment by cathaysia** [comment]
yes, I can see 0x0a by xxd, but I noticed that when open this file by vscode, it will has a blank line, but nvim does not. Can I make neovim has this behaviour?

![图片](https://user-images.githubusercontent.com/42114817/205474001-5045aef5-540e-44d7-bcb7-04ff90d4e9d8.png)
![图片](https://user-images.githubusercontent.com/42114817/205474007-5f094281-74de-4539-95dd-68a01066a0a6.png)

**Comment by gpanders** [comment]
I don’t know what VS Code is doing. However, at this point it’s no longer an issue with this plugin but a more general Neovim question. Try asking on [Reddit](https://reddit.com/r/neovim), the [Neovim Discourse](https://neovim.discourse.group), or the [Neovim Matrix](https://matrix.to/#/#neovim:matrix.org) channel.

**Comment by cathaysia** [comment]
ok，thanks
________________________________
