### ISSUE TITLE
Add some indicator that the settings have been changed

### ISSUE THREAD

**Issue by nogweii** [gpanders/editorconfig.nvim#5]
I'm hoping to pair this plugin with a couple of other features:

* Guessing the file's settings from the existing contents
* Falling back to global defaults otherwise

This way if I open a file that does not conform to the settings in `.editorconfig`, but I do have a file in the project, new code written will conform (since my editor has the settings applied). If I'm editing existing code in a project that doesn't have an editorconfig file, then smartly-guessed settings should apply.

I think adding a buffer-local variable indicating editorconfig.nvim has ran could work, or perhaps providing a User autocmd?

**Comment by gpanders** [comment]
I added a `b:editorconfig` buffer variable in fd56950ca2427114f7d2e34aba312df3c2788cdb.
