### ISSUE TITLE
Please allow to change the default configuration

### ISSUE THREAD

**Issue by cryptomilk** [gpanders/editorconfig.nvim#7]
Hi,

I would expect that if there is no `.editorconfig`, that I can set defaults, like:

```lua
require('editorconfig').setup({
    insert_final_newline = true,
})
```

**Comment by gpanders** [comment]
Sorry, this plugin’s sole raison d'être is to parse and read EditorConfig files. Neovim already contains mechanisms for setting “fallback” settings (either globally or per filetype), so there’s no reason for this plugin to reinvent that wheel.
