### ISSUE TITLE
Error: invalid value for option end_of_line: auto

### ISSUE THREAD

**Issue by daephx** [gpanders/editorconfig.nvim#8]
Plugin in complaining of invalid option values when starting neovim.
This doesn't occur when using editorconfig.vim.

```
editorconfig: invalid value for option end_of_line: auto
```

**Comment by gpanders** [comment]
The [EditorConfig specification](https://editorconfig.org) doesn't mention `auto` as a valid value for `end_of_line` (nor does their [wiki](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties)). I suspect this is an editorconfig-vim specific extension.

What is the "auto" value supposed to do?

**Comment by daephx** [comment]
Hmm, while looking into these plugins I found some example `.editorconfig`'s that included the `auto` setting.
I was unaware that it wasn't in the spec.

Looking at [editorconfig/editorconfig.vim](https://github.com/editorconfig/editorconfig-vim) there is no reference to `auto`; so my assumption is that the option just falls through the conditions and doesn't match the main three `lf`, `crlf`, `cr` and ultimately gets ignored without returning any kind of error message.

https://github.com/editorconfig/editorconfig-vim/blob/a8e3e66deefb6122f476c27cee505aaae93f7109/plugin/editorconfig.vim#L408-L417

**Comment by daephx** [comment]
If it's not in spec then there's no issue.
At least this can serve as a reference if anyone else encounters the confusion.
