### ISSUE TITLE
Installation with package manager, and clarification regarding setup call

### ISSUE THREAD

**Issue by krishnakumarg1984** [gpanders/editorconfig.nvim#9]
Hi,

Thanks a lot for developing this plugin. May I please request for some installation notes (examples) in the project's README? 

In my `init.lua` with `packer` as the package manager, I currently have:

```lua
use {
        "gpanders/editorconfig.nvim",
        event = { "InsertCharPre" },
      },
```

Is this sufficient? Should I also call the plugin' setup() like `require(editorconfig).setup()` somewhere in my `init.lua`?

**Comment by gpanders** [comment]
You do not need to lazy load this plugin, and there is no need for a setup call.

Deferring until InsertCharPre will have cause other problems anyway (EditorConfig controls things that can be used without ever entering insert mode).

Loading on-demand (and having a minimal footprint unless/until it is used) is the responsibility of the plugin itself. Unfortunately, many plugins shirk this responsibility and packer has tried to step in to help mediate that problem, but rest assured editorconfig.nvim is doing everything possible to not waste a millisecond of your startuptime unless absolutely necessary.
